version: "3.8"
services:
  wdio:
    build: .
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    entrypoint: ["npm", "run", "wdio"]
    environment:
      - NODE_ENV=production
    ports:
      - "4444:4444"
